export const env = {
  CLOUD_API_KEY: process.env?.REACT_APP_CL_API_KEY,
  CLOUD_AUTH_DOMAIN: process.env?.REACT_APP_CL_AUTH_DOMAIN,
  CLOUD_PROJECT_ID: process.env?.REACT_APP_CL_PROJECT_ID,
  CLOUD_STORAGE_BUCKET: process.env?.REACT_APP_CL_STORAGE_BUCKET,
  CLOUD_MESSAGING_SENDER_ID: process.env?.REACT_APP_CL_MESSAGING_SENDER_ID,
  CLOUD_APP_ID: process.env?.REACT_APP_CL_APP_ID,
  CLOUD_MEASUREMENT_ID: process.env?.REACT_APP_CL_MEASUREMENT_ID,
  MAILING_SERVER_URL: process.env?.REACT_APP_MAILING_SERVER_URL ?? "",
};
